/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Tasks36367AtlasCodeReviewRouteImport } from './routes/tasks/36367-atlas-code-review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Tasks36367AtlasCodeReviewRoute =
  Tasks36367AtlasCodeReviewRouteImport.update({
    id: '/tasks/36367-atlas-code-review',
    path: '/tasks/36367-atlas-code-review',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tasks/36367-atlas-code-review': typeof Tasks36367AtlasCodeReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tasks/36367-atlas-code-review': typeof Tasks36367AtlasCodeReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tasks/36367-atlas-code-review': typeof Tasks36367AtlasCodeReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tasks/36367-atlas-code-review'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tasks/36367-atlas-code-review'
  id: '__root__' | '/' | '/tasks/36367-atlas-code-review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Tasks36367AtlasCodeReviewRoute: typeof Tasks36367AtlasCodeReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/36367-atlas-code-review': {
      id: '/tasks/36367-atlas-code-review'
      path: '/tasks/36367-atlas-code-review'
      fullPath: '/tasks/36367-atlas-code-review'
      preLoaderRoute: typeof Tasks36367AtlasCodeReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Tasks36367AtlasCodeReviewRoute: Tasks36367AtlasCodeReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
